### Numpy

In [1]:
import numpy as np

### List vs Array

In [9]:
x = np.array(10)
print(x)

10


In [6]:
zero =  np.zeros((4,2))
print(zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
one = np.ones((3,5), dtype=int)
print(one)

onef =  np.ones((4,2))
print(onef)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
empty = np.empty((2,4))
print(empty)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
arr1  = np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]
