- Ali Abid


In [28]:
import numpy as np

### Q1

In [29]:
x1 = np.array([[10,20], [11,22], [40,60], [40,20]])
print(x1,"\n")

print(f"Shape: {x1.shape}")
print(f"Dimension: {x1.ndim}")
print(f"e length in bytes: {x1.itemsize}")

[[10 20]
 [11 22]
 [40 60]
 [40 20]] 

Shape: (4, 2)
Dimension: 2
e length in bytes: 8


### Q2

In [35]:
x2 = np.arange(100, 200, 10).reshape(5,2)
print(x2)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


# Q3

In [ ]:
sampleArray = np.array([[11 ,22, 33],
                           [44, 55, 66],
                          [77, 88, 99]])
x3 = sampleArray[0:3, 2]

print(x3)

[33 66 99]
